layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  include:  
    projects:
      - acl2020-contextnmt-cataphora
      - offshoreleaks-viz
      - physionet-rnn 
      
  exclude:
    archived: false
    forks: false
    projects:
    # -

social_media:
  twitter: 0xkaywong
  linkedin: kayyenwong
  googlescholar: 0cKOXhIAAAAJ
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Natural Language Processing
    web_url: https://github.com/topics/nlp

  - name: Machine Learning
    web_url: https://github.com/topics/machine-learning
  
  - name: Civic Tech
    web_url: https://github.com/topics/civic-tech
    #image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png
  




  