layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
  - jekyll-feed

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

bio: "An experienced programmer with a demonstrated history of research and industry experience in Machine Learning. I’m passionate about Machine Learning, Natural Language Processing, and Civic Technology. I completed my Bachelors in Computer Science (Honours) at Monash University Australia, with a thesis focused in Neural Machine Translation."

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  included:  
    projects:
      - Wiki-Reliability
      - offshoreleaks-viz
      - physionet-rnn 
      - acl2020-contextnmt-cataphora    
  exclude:
    archived: false
    forks: false
    projects:
    # -

social_media:
  twitter: 0xkaywong
  linkedin: kayyenwong
  googlescholar: 0cKOXhIAAAAJ
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:

  - name: Machine Learning
    web_url: https://github.com/topics/machine-learning
    image_url: ./images/machine-learning.png

  - name: Natural Language Processing
    web_url: https://github.com/topics/nlp
    image_url: ./images/natural-language-processing.png
  
  - name: Civic Tech
    web_url: https://github.com/topics/civic-tech
    image_url: ./images/civictech.png
  

publications:

  - title: "Contextual Neural Machine Translation Improves Translation of Cataphoric Pronouns"
    web_url: https://www.aclweb.org/anthology/2020.acl-main.530/ 
    abstract: "In Proceedings of the 58th Conference of the Association for Computational Linguistics (ACL2020)."
    authors: "KayYen Wong, Sameen Maruf, Gholamreza Haffari"
    date: "Jul, 2020"
  
  - title: "The State of Internet Censorship in Indonesia"
    web_url: https://ooni.org/post/indonesia-internet-censorship
    abstract: "A research study by the Open Observatory of Network Interference (OONI) and Sinar Project."
    authors: "Kay Yen Wong, Maria Xynou, Arturo Filastò, Khairil Yusof, Tan Sze Ming"
    date: "May 23, 2017"

  - title: "The State of Internet Censorship in Myanmar"
    web_url: https://ooni.org/post/myanmar-report/
    abstract: "A research study by the Open Observatory of Network Interference (OONI), Sinar Project, and the Myanmar ICT for Development Organization (MIDO)."
    authors: "Kay Yen Wong, Maria Xynou, Arturo Filastò, Khairil Yusof, Tan Sze Ming, MIDO"
    date: "Mar 29, 2017"

  - title: "The State of Internet Censorship in Thailand"
    web_url: https://ooni.org/post/thailand-internet-censorship/
    abstract: "A research study by the Open Observatory of Network Interference (OONI), Sinar Project, and the Thai Netizen Network"
    authors: "Kay Yen Wong, Maria Xynou, Arturo Filastò, Khairil Yusof, Tan Sze Ming, Thai Netizen Network"
    date: "Mar 20, 2017"



  